MusicosChile/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from rest_framework import routers
from quick import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('index/', include('index.urls')),
    path('accounts/', include('sesion.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='ind'),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]



urlpatterns+= static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

index/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('perfil/', views.perfil, name='perfil'),
    path('buscar/', views.buscar, name='buscar'),
    path('registro/', views.registro, name='registro'),
    path('mensajes/', views.mensajes, name='mensajes'),
    path('admin/', views.admin, name='admin'),
    path('musico/<str:pk>', views.ConsultarMusico.as_view(), name='consultar_musico'),
    path('mensaje/<str:pk>', views.ConsultarMensaje.as_view(), name='consultar_mensaje'),
    
]

urlpatterns+=[
    path('musico/create/', views.CrearMusico.as_view(), name='crear_musico'),
    path('musico/<str:pk>/update/', views.ActualizarMusico.as_view(), name='actualizar_musico'),
    path('musico/<str:pk>/delete/', views.EliminarMusico.as_view(), name='eliminar_musico'),

    path('mensaje/create/', views.CrearMensaje.as_view(), name='crear_mensaje'),
    path('mensaje/<str:pk>/update/', views.ActualizarMensaje.as_view(), name='actualizar_mensaje'),
    path('mensaje/<str:pk>/delete/', views.EliminarMensaje.as_view(), name='eliminar_mensaje'),
    
    

]

index/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances

'''
# Create your models here.
class Genre(models.Model):
    #Model representing a book genre."""
	name = models.CharField(max_length=200)
	
	def __str__(self):
		return self.name

class Book(models.Model):
    
	title = models.CharField(max_length=200)
	author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    
	summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
	isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
	genre = models.ManyToManyField(Genre)
    
	def __str__(self):
		return self.title
    
	def get_absolute_url(self):
		"""Returns the url to access a detail record for this book."""
		return reverse('book-detail', args=[str(self.id)])


class BookInstance(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
	book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
	imprint = models.CharField(max_length=200)
	due_back = models.DateField(null=True, blank=True)

	LOAN_STATUS = (
		('m', 'Maintenance'),
		('o', 'On loan'),
		('a', 'Available'),
		('r', 'Reserved'),
	)

	status = models.CharField(
		max_length=1,
		choices=LOAN_STATUS,
		blank=True,
		default='m',
		help_text='Book availability',
	)

	class Meta:
		ordering = ['due_back']

	def __str__(self):
		"""String for representing the Model object."""
		return f'{self.id} ({self.book.title})'


class Author(models.Model):
	"""Model representing an author."""
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death = models.DateField('Died', null=True, blank=True)

	class Meta:
		ordering = ['last_name', 'first_name']

	def get_absolute_url(self):
		return reverse('author-detail', args=[str(self.id)])

	def __str__(self):
		"""String for representing the Model object."""
		return f'{self.last_name}, {self.first_name}'	

'''
class Musico(models.Model):
	usuario = models.CharField(max_length=100, primary_key=True)
	nombres = models.CharField(max_length=100)
	apellidos = models.CharField(max_length=100)
	edad = models.CharField(max_length=100)	
	contraseña = models.CharField(max_length=100)
	celular = models.CharField(max_length=100)	
	correo = models.CharField(max_length=100)	
	region = models.CharField(max_length=100)	

	def __str__(self):
		return self.usuario		

class Mensaje(models.Model):
	id = models.CharField(max_length=100, primary_key=True)
	usuario = models.CharField(max_length=100)
	
	texto = models.CharField(max_length=100)
	fecha = models.DateField(null=True, blank=True)

	def __str__(self):
		return self.id

index/templates/index/author_confirm_delete.html
{%extends "base_generic.html%}

{%block content%}
<h1> Delete Author </h1>
<p>Are you sure you want to delete the author: {{author}} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" action="" value="Delete">
</form>
{%endblock%}

index/templates/index/mensaje_confirm_delete.html
{% extends "base_generic.html" %}

{%block content%}
<Div id="cajadatos">
<h1> Eliminar mensaje </h1>
<p style="color: rgb(255, 255, 255);">¿Estas seguro de que quieres eliminar el mensaje N° {{mensaje}} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" action="" value="Eliminar">
</form>
</Div>
{%endblock%}

index/templates/index/mensaje_detail.html
{%extends "base_generic.html"%}

{%block content%}
<div id="cajadatos">
<h1>Detalles de mensaje</h1>
<br>
<h2 style="color: rgb(255, 255, 255);">mensaje N°: {{mensaje.id}}</h2>
<h2 style="color: rgb(255, 255, 255);">Usuario: {{mensaje.usuario}}</h2>
<h2 style="color: rgb(255, 255, 255);">Contenido: {{mensaje.texto}}</h2>
<h2 style="color: rgb(255, 255, 255);">Fecha: {{mensaje.fecha}}</h2>

</div>

<!--
<div style="margin-left:20px;margin-top:20px">
<h4>Books</h4>
    <dl>
        {%for book in author.book_set.all%}
            <dt><a href="{%url 'book-detail' book.pk %}">{{book}}</a>
                ({{book.bookinstance_set.all.count}})</dt>
                <dd>{{book.summary}}</dd>
        {%endfor%}    

    </dl>
</div>
-->
{%endblock%}

index/templates/index/mensaje_form.html
{% extends "base_generic.html" %}

{% block content%}
<p></p>
<div id="cajadatos">
<h1>Creando Mensaje</h1>
<div class="col-lg-4"  style="background-color:#3c9cdb">
<form action ="" method="post">
    {%csrf_token%}
    <table>
        {{form.as_table}}

    </table>
    <br>
    <input type="submit" value ="Enviar">
    <br>
</form>
<br>
</div>
</div>

{%endblock%}

index/templates/index/mensaje_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>mensaje List</h1>

    {% if mensaje_list %}
    <ul>

      {% for mensaje in mensaje_list %}
      <li>
        <a href="{{ mensaje.get_absolute_url }}">{{ mensaje.id }}</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

index/templates/index/musico_confirm_delete.html
{% extends "base_generic.html" %}

{%block content%}
<Div id="cajadatos">
<h1> Eliminar músico </h1>
<p style="color: rgb(255, 255, 255);">¿Estas seguro de que quieres eliminar al usuario: {{musico}} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" action="" value="Eliminar">
</form>
</Div>
{%endblock%}

index/templates/index/musico_detail.html
{%extends "base_generic.html"%}

{%block content%}
<div id="cajadatos">
<h1>Detalles de Músico</h1>
<br>
<h2 style="color: rgb(255, 255, 255);">Usuario: {{musico}}</h2>
<h2 style="color: rgb(255, 255, 255);">Nombres: {{musico.nombres}}</h2>
<h2 style="color: rgb(255, 255, 255);">Apellidos: {{musico.apellidos}}</h2>
<h2 style="color: rgb(255, 255, 255);">Edad: {{musico.edad}}</h2>
<h2 style="color: rgb(255, 255, 255);">Contraseña: {{musico.contraseña}}</h2>
<h2 style="color: rgb(255, 255, 255);">Numero Celular: {{musico.celular}}</h2>
<h2 style="color: rgb(255, 255, 255);">Correo electronico: {{musico.correo}}</h2>
<h2 style="color: rgb(255, 255, 255);">Region: {{musico.region}}</h2>
</div>
<!--
<div style="margin-left:20px;margin-top:20px">
<h4>Books</h4>
    <dl>
        {%for book in author.book_set.all%}
            <dt><a href="{%url 'book-detail' book.pk %}">{{book}}</a>
                ({{book.bookinstance_set.all.count}})</dt>
                <dd>{{book.summary}}</dd>
        {%endfor%}    

    </dl>
</div>
-->
{%endblock%}

index/templates/index/musico_form.html
{% extends "base_generic.html" %}

{% block content%}
<p></p>
<div id="cajadatos">
<h1>Crear Músico</h1>

<div class="col-lg-4"  style="background-color:#3c9cdb">
<form action ="" method="post">
    {%csrf_token%}
    <table>
        {{form.as_table}}

    </table>
    <br>
    <input type="submit" value ="Enviar">
    <br>
</form>
<br>
</div>    
</div>
{%endblock%}

index/templates/index/musico_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>musico List</h1>

    {% if musico_list %}
    <ul>

      {% for musico in musico_list %}
      <li>
        <a href="{{ musico.get_absolute_url }}">{{ musico.usuario }}</a> 
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}